name: lights
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.1
  flutter_tts: ^3.3.3
  shared_preferences: ^2.0.11
  http: ^0.13.4
  flutter_phone_direct_caller: ^2.1.0
  camera: ^0.9.4+5
  tflite: ^1.1.2
  image_picker: ^0.8.4+4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/ssd_mobilenet.tflite
    - assets/labels.txt
